repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: |
          (?x)^(
            .*/template\.ya?ml|
            infrastructure/.*\.ya?ml|
            templates/.*\.ya?ml
          )
      - id: check-added-large-files
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]

  # CloudFormation-specific linting
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v1.34.2
    hooks:
      - id: cfn-lint
        files: |
          (?x)^(
            .*/template\.ya?ml|
            infrastructure/.*\.ya?ml|
            templates/.*\.ya?ml
          )
