name: CI on Push for Feature Branch

on:
  push:
    branches:
      - "**"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Format code
        run: |
          black . --check --diff # Mimics the check performed with pre-commit hook

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Apply Pre-commit linting
        run: pre-commit run --all-files --show-diff-on-failure --verbose

      - name: Apply Ruff linting
        run: ruff check .

      - name: Apply cfn-lint linting
        run: |
          find . -type f \( \
            -path "*/template.yaml" -o -path "*/template.yaml" -o \
            -path "infrastructure/*.yaml" -o -path "infrastructure/*.yaml" -o \
            -path "templates/*.yaml" -o -path "templates/*.yaml" \
          \) -print0 | xargs -0 cfn-lint

      - name: Check types with Mypy
        run: mypy . --ignore-missing-imports

  # security-scan:
  # test:
  # build:
