name: CI on Push for Feature Branch

on:
  push:
    branches:
      - "**"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -r services/show_service/requirements-dev.txt

      - name: Format code
        run: |
          black services/show_service --check --diff # Mimics the check performed with pre-commit hook

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -r services/show_service/requirements-dev.txt

      - name: Apply Pre-commit linting
        run: pre-commit run --all-files --show-diff-on-failure --verbose

      - name: Apply Ruff linting
        run: ruff check services/show_service

      - name: Apply cfn-lint linting
        run: |
          find services/show_service -type f \( \
            -path "*/template.yaml" -o -path "*/template.yml" -o \
            -path "infrastructure/*.yaml" -o -path "infrastructure/*.yml" -o \
            -path "templates/*.yaml" -o -path "templates/*.yml" \
          \) -print0 | xargs -0 cfn-lint -v

      - name: Check types with Mypy
        run: mypy services/show_service --ignore-missing-imports

  # security-scan:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -r services/show_service/hello_world/requirements.txt
          pip install -r services/show_service/tests/requirements.txt

      - name: Run unit tests
        run: pytest -v
  # build:
